version: '3.4'

services:
  webengineering:
    image: webengineering
    build:
      context: WebEng
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
  
  frontend:
    image: frontend
    build:
      context: WebEng/frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
